name: hive_gen_works
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  auto_route: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true